local M = {}

M.get_colors = function(s)
    local group_colors = {
        TreesitterContext = { bg = s.purple500 },

        ["@none"]                         = {},

        ["@boolean"]                      = { link = "Boolean" },
        ["@character"]                    = { link = "Character" },
        ["@character.special"]            = { link = "SpecialChar" },
        ["@constant"]                     = { link = "Constant" },
        ["@constant.builtin"]             = { link = "Special" },
        ["@constant.macro"]               = { link = "Define" },
        ["@number"]                       = { link = "Number" },
        ["@number.float"]                 = { link = "Number" },
        -- ["@property"]                     = { link = "Identifier" },
        ["@string"]                       = { link = "String" },
        ["@string.documentation"]         = { link = "Comment" },
        ["@string.escape"]                = { fg = s.red500 },
        -- ["@string.regexp"]                = { fg = s.cyan500 },
        ["@type"]                         = { fg = s.blue500 },
        -- ["@type.builtin"]                 = { link = "Type" },
        -- ["@type.definition"]              = { link = "Typedef" },
        -- ["@type.qualifier"]               = { fg = s.orange500 },
        ["@variable"]                     = { fg = s.fg500 },
        -- ["@variable.builtin"]             = { fg = s.orange500 },
        -- ["@variable.javascript"]          = { fg = s.yellow500 },
        ["@variable.member"]              = { fg = s.magenta500 },
        ["@variable.parameter"]           = { fg = s.fg500 },
        -- ["@variable.parameter.builtin"]   = { fg = s.yellow500 },
        -- ["@variable.typescript"]          = { fg = s.yellow500 },

        -- ["@annotation"]                   = { link = "PreProc" },
        -- ["@attribute"]                    = { link = "PreProc" },
        ["@constructor"]                  = { fg = s.magenta500 },
        -- ["@constructor.tsx"]              = { fg = s.red500 },
        ["@function"]                     = { link = "Function" },
        -- ["@function.builtin"]             = { link = "Special" },
        ["@function.call"]                = { link = "@function" },
        -- ["@function.macro"]               = { link = "Macro" },
        ["@function.method"]              = { fg = s.fg500 },
        ["@function.method.call"]         = { fg = s.magenta500 },
        ["@keyword"]                      = { fg = s.blue500 },
        ["@keyword.conditional"]          = { fg = s.blue500 },
        -- ["@keyword.coroutine"]            = { link = "@keyword" },
        ["@keyword.debug"]                = { link = "Debug" },
        ["@keyword.directive"]            = { fg = s.green500 },
        ["@keyword.directive.define"]     = { link = "@keyword.directive" },
        ["@keyword.exception"]            = { link = "Exception" },
        ["@keyword.function"]             = { fg = s.blue500 },
        ["@keyword.import"]               = { link = "Include" },
        -- ["@keyword.javascript"]           = { fg = s.green500, italic = true },
        ["@keyword.operator"]             = { link = "@keyword" },
        ["@keyword.repeat"]               = { link = "@keyword" },
        ["@keyword.return"]               = { link = "@keyword" },
        -- ["@keyword.return.javascript"]    = { fg = s.green500, italic = true },
        -- ["@keyword.return.tsx"]           = { fg = s.green500, italic = true },
        -- ["@keyword.storage"]              = { link = "StorageClass" },
        -- ["@keyword.tsx"]                  = { fg = s.green500, italic = true },
        -- ["@label"]                        = { fg = s.green500 },
        ["@module"]                       = { fg = s.green500 },
        -- ["@module.builtin"]               = { fg = s.orange700 },
        -- ["@namespace.builtin"]            = { fg = s.red500 },

        ["@comment"]                      = { link = "Comment", italic = true },
        ["@comment.error"]                = { fg = s.red500 },
        ["@comment.hint"]                 = { fg = s.yellow500 },
        ["@comment.info"]                 = { fg = s.green500 },
        ["@comment.note"]                 = { fg = s.foreground },
        ["@comment.todo"]                 = { fg = s.orange500 },
        ["@comment.warning"]              = { fg = s.yellow500 },

        ["@diff.delta"]                   = { link = "DiffChange" },
        ["@diff.minus"]                   = { link = "DiffDelete" },
        ["@diff.plus"]                    = { link = "DiffAdd" },

        ["@markup"]                       = {},
        ["@markup.environment"]           = { link = "Macro" },
        ["@markup.environment.name"]      = { link = "Type" },
        ["@markup.heading"]               = { fg = s.green500 },
        ["@markup.italic"]                = { italic = true },
        ["@markup.link"]                  = { fg = s.blue500, underline = false },
        ["@markup.link.label"]            = { fg = s.blue500, underline = false },
        ["@markup.link.label.symbol"]     = { fg = s.orange500 },
        ["@markup.link.url"]              = { fg = s.green500 },
        ["@markup.list"]                  = { fg = s.blue500, bold = true },
        ["@markup.list.checked"]          = { fg = s.green500 },
        ["@markup.list.markdown"]         = { fg = s.orange500, bold = true },
        ["@markup.list.unchecked"]        = { fg = s.red500 },
        ["@markup.math"]                  = { link = "Special" },
        ["@markup.raw"]                   = { link = "String" },
        ["@markup.raw.markdown"]          = { fg = s.green500 },
        ["@markup.raw.markdown_inline"]   = { fg = s.blue500 },
        ["@markup.strikethrough"]         = { strikethrough = true },
        ["@markup.strong"]                = { bold = true },
        ["@markup.underline"]             = { underline = true },

        -- ["@punctuation.bracket"]          = { fg = s.orange500 },
        -- ["@punctuation.delimiter"]        = { fg = s.green500 },
        -- ["@punctuation.special"]          = { fg = s.orange500, bold = true },
        -- ["@punctuation.special.markdown"] = { fg = s.orange500, bold = true },

        -- ["@tag"]                          = { link = "Label" },
        -- ["@tag.attribute"]                = { link = "Identifier" },
        -- ["@tag.delimiter"]                = { link = "Delimiter" },
        -- ["@tag.delimiter.html"]           = { fg = s.orange500 },
        -- ["@tag.delimiter.javascript"]     = { fg = s.orange500 },
        -- ["@tag.delimiter.tsx"]            = { fg = s.orange500 },
        -- ["@tag.delimiter.vue"]            = { fg = s.orange500 },
        -- ["@tag.javascript"]               = { fg = s.yellow500 },
        -- ["@tag.tsx"]                      = { fg = s.yellow500 },
    }
    return group_colors
end

return M
